### ISSUE TITLE
Input fields data not appear on emails

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/product-input-fields-for-woocommerce#101]
**Describe the bug**
This is an issue that was reported by one of our users on the WP forum claiming that product input field data are not being added to the list of order info shown on the order emails. The user was able to fix this by changing a line of code on the **class-alg-wc-pif-main.php** file.

`add_action( 'woocommerce_order_item_meta_end', array( $this, 'output_custom_input_fields_in_admin_order' ), 10, 3 );`

The exact line of code can be located on line 70 of _includes/class-alg-wc-pif-main.php_.

**P.S.** I was unable to reproduce the issue on my end with the same version (v1.5.0) the user pointed out.

**Additional context**
[https://wordpress.org/support/topic/fixing-the-issue-with-emails-not-showing-input-fields/](https://wordpress.org/support/topic/fixing-the-issue-with-emails-not-showing-input-fields/)

**Comment by oluisrael11** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitHub issue - 101](https://trello.com/c/2xPDDYlz/9-github-issue-101)

**Comment by oluisrael11** [comment]
Another user reported this issue - [https://tychesoftwares.freshdesk.com/a/tickets/56979](https://tychesoftwares.freshdesk.com/a/tickets/56979)

**Comment by mital-tyche** [comment]
This one is not replicated on our side I checked with latest version of woocommerce - v8.0.3
And latest version of plugin v1.6.0.

**Comment by ashokrane** [comment]
@mital-tyche @oluisrael11 2 customers have reported this same issue. It's likely that we are missing something when testing it.

The 2nd customer in ticket 56979 has said that they are using our other plugins too like Prdd & Ordd. Have you tried with those plugins?

**Comment by oluisrael11** [comment]
@ashokrane @mital-tyche I have been able to remodel this again on my end and can confirm that it isn't a bug in our plugin; at least based on the tests I have carried out on my end so far. The issue only seems to happen when both the global and local input field settings are enabled at the same time and for the same input field type.
​
This means that if _All Products: Field # 1_ is active for the **text field input field type**, and the exact same field type is also active on any other product, then the issue will appear on the product page frontend. So the proper way to get this sorted out is to disable the input field type on the product on which the local input field settings is enabled while ensuring that the only active one is the global setting.

<img width="654" alt="image" src="https://github.com/TycheSoftwares/product-input-fields-for-woocommerce/assets/12012702/27976fcc-ac07-44b6-b44f-f0ca4be3c932">

<img width="751" alt="image" src="https://github.com/TycheSoftwares/product-input-fields-for-woocommerce/assets/12012702/5082c765-e05b-409f-b154-95bcb1aaa821">

<img width="1032" alt="image" src="https://github.com/TycheSoftwares/product-input-fields-for-woocommerce/assets/12012702/327abbdf-2918-408f-88c2-5da174745403">


If I disable the input field on the edit product page for the Test Product 2 above, the issue becomes instantly becomes nonexistent.

**Comment by oluisrael11** [comment]
@mital-tyche @ashokrane I tried to recreate the issue with both PRDD and ORDD plugins installed and active but still couldn't. The input field data were correctly added to the order confirmation emails and nothing strange was noticed.

I'll get the client to share his site credentials with me to check if I can pick out why this keeps happening.

**Comment by ashokrane** [comment]
Ok, thanks @oluisrael11 . Appreciate it.

**Comment by oluisrael11** [comment]
@mital-tyche one of the affected users fixed the issue with the code below:

```
add_action( 'woocommerce_before_order_itemmeta', array( $this, 'output_custom_input_fields_in_admin_order' ), 10, 3 );
            //add_action( 'woocommerce_checkout_update_order_meta', array( $this, 'update_order_meta_fields' ), 10, 2 );
            //Line over commented out vk:4.9.2023, line under inserted
            add_action( 'woocommerce_order_item_meta_end', array( $this, 'output_custom_input_fields_in_admin_order' ), 10, 3 );
```

Could you please review it and then we see if it is something we can consider?

**Comment by oluisrael11** [comment]
Another user reported this issue — [https://tychesoftwares.freshdesk.com/a/tickets/57448](https://tychesoftwares.freshdesk.com/a/tickets/57448)

**Comment by oluisrael11** [comment]
Another user reported this issue — [https://tychesoftwares.freshdesk.com/a/tickets/56668](https://tychesoftwares.freshdesk.com/a/tickets/56668)

**Comment by apeksha10** [comment]
Re-opening this issue.

>Also, while checking the issue, I noticed that the custom input fields are also not displayed on the order confirmation page.
This is not working. I have tested with File input field, Text Input field, and Text area input field
https://app.screencast.com/R3Q7Va6l0xkSg
