### ISSUE TITLE
Bug with the datepicker

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/product-input-fields-for-woocommerce#121]
**Describe the bug**
There is a bug with the date picker input field that forces all dates selected on the calendar to return **j F Y** or **F j, Y** on the input field and not the selected dates.

<img width="1182" alt="image" src="https://github.com/TycheSoftwares/product-input-fields-for-woocommerce/assets/12012702/4690503b-1557-4753-8018-757597c6794e">

**To Reproduce**
1. Edit any product and select the datepicker input field instead.
2. You can choose to enter a date format or skip it since whatever is entered there will be returned on the product page frontend.
<img width="721" alt="image" src="https://github.com/TycheSoftwares/product-input-fields-for-woocommerce/assets/12012702/7a6613e0-adbb-4b99-a1f9-67ef77225b66">

3. Navigate to the checkout page to see the error.

**Additional context**
[https://tychesoftwares.freshdesk.com/a/tickets/62214](https://tychesoftwares.freshdesk.com/a/tickets/62214)

**Comment by oluisrael11** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitHub issue - 121](https://trello.com/c/TQqcLItE/17-github-issue-121)

**Comment by oluisrael11** [comment]
Another user reported this issue - [https://support.tychesoftwares.com/conversation/557?folder_id=17](https://support.tychesoftwares.com/conversation/557?folder_id=17)

**Comment by gaminikhil** [comment]
This issue has been fixed in #113
