### ISSUE TITLE
Need to update the 'Tested up to' tag in readme file and as well as the WooCommerce tested upto tag.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/product-input-fields-for-woocommerce#14]
Need to update the 'Tested up to' tag in readme file and as well as the WooCommerce tested up to tag.

Forum: https://wordpress.org/support/topic/not-compatible-with-the-most-recent-version-of-wp/

**Comment by Shasvat7** [comment]
In the latest v1.2.7, the 'Tested up to' tag in the readme file and the WC tested up to tag have proper value, hence closing this issue as it is no longer valid.
