### ISSUE TITLE
The custom input field is not changing the position which is before add to cart button and after the global product add-ons options and adding any value to the 'Priority' setting.

### ISSUE THREAD

**Issue by moxajogani** [TycheSoftwares/product-input-fields-for-woocommerce#18]
The custom input field is not changing the position which is before add to cart button and after the global product add-ons options and adding any value to the 'Priority' setting.

Product add-ons plugin is activated.

Checked on the client's staging site, adding any value to the 'Priority' setting, the placement of custom input field is not changing to the options from the Product add-ons plugin.

Ticket: https://tychesoftwares.freshdesk.com/a/tickets/7965

**Comment by PratapDungrani** [comment]
@kartikparmar @moxajogani could you provide product add-on plugin please?

Thanks

**Comment by kartikparmar** [comment]
[woocommerce-product-addons-v4.9.0.zip](https://github.com/TycheSoftwares/product-input-fields-for-woocommerce/files/8530397/woocommerce-product-addons-v4.9.0.zip)

**Comment by PratapDungrani** [comment]
@kartikparmar Priority is working even with the product add-on plugin. The product add-on plugin has a priority set to 10 so the user needs to set a higher priority if wants our field right above add to cart button. Let me know. Thanks

**Comment by PratapDungrani** [comment]
Though I noticed that for a product with variation, our field stick to the add to cart button. But this is not our issue. Product add-on plugin could have the lowest priority for variable products.
