### ISSUE TITLE
Our plugin is conflicting with the Creta theme.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/product-input-fields-for-woocommerce#26]
The value entered into the input field on the product page is displaying improperly in the mini cart.
Screenshot: https://www.screencast.com/t/sLI0KMQiEXr

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/14015

[creta.zip](https://github.com/TycheSoftwares/product-input-fields-for-woocommerce/files/4266355/creta.zip)

**Comment by dhruvins** [comment]
Closed in https://github.com/TycheSoftwares/product-input-fields-for-woocommerce/pull/27
