### ISSUE TITLE
Security vulnerability in the plugin

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/product-input-fields-for-woocommerce#33]
The client has informed us that the vulnerability is found in the plugin.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/18918

**Comment by rajanshri** [comment]
@kenil802 this issue has been fixed and added a filter "alg_wc_pif_download_extra_extensions" to allow extra extensions to be downloaded. New branch for this issue can be downloaded from [here](https://github.com/TycheSoftwares/product-input-fields-for-woocommerce/tree/issue-%2333)

Currently user can download files with following extensions 'jpg', 'jpeg', 'gif', 'png', 'mp3', 'mp4', 'doc', 'docx', 'xlsx', 'xls', 'ppt', 'pptx'.
