### ISSUE TITLE
Additional description is shown on all the products even after disabling the All products setting.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/product-input-fields-for-woocommerce#42]
The issue is that the description which we add in the setting "HTML to add before the product input fields" is shown on all the products even if we disable the All Product settings.

Steps to replicate the issue:
1) Add any additional content to the setting "HTML to add before the product input fields": https://prnt.sc/uji035
2) Enable the Per Product setting:  https://prnt.sc/uji0k0
3) Disable the All Product setting: https://prnt.sc/uji10a
4) You will the additional text on all the products even if that product does not have the input field: https://prnt.sc/uji29l

This additional text should not get displayed if we have not enabled the input field on that particular product.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/20777

**Comment by apeksha10** [comment]
After taking the latest git copy,
Follow same steps as the issue has 
see the All screenshot : 
Product fronend : https://www.screencast.com/t/A7mQW8AzP
 https://www.screencast.com/t/wnl6TtIAo5c,  https://www.screencast.com/t/GsSasP2r3
https://www.screencast.com/t/yIh7lHa0lV
https://www.screencast.com/t/9tDhX7qTw4

**Comment by Shasvat7** [comment]
@apeksha10 I am unable to replicate the above issue with the latest git copy, here you can check the video: https://www.awesomescreenshot.com/video/3104063?key=4699bd591e085f50d48f365297d4ad37
So please check it once again with the latest git copy.

**Comment by apeksha10** [comment]
Hi all,

@vishal Sir had tested the above issue with the latest git copy and he has not able to replicate the above issue.

Hence I have closed this issue and I have put a fixed label.
