### ISSUE TITLE
Input field data does not show in the XML file.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/product-input-fields-for-woocommerce#45]
**Describe the bug**
The issue is when we export the order in the XML file, the input field data is not showing in that XML file.

**To Reproduce**
1. Setup the input field for any product.
2. Add the product to the cart along with the value of the input field.
3. Place an order.
4. Export the orders from Tools >> Export >> Orders.
5. You will not find the input field value in that XML file.

**Expected behavior**
The input field value should get displayed in the XML file.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/25312

**Comment by oluisrael11** [comment]
Another client also reported this issue — [https://tychesoftwares.freshdesk.com/a/tickets/37260](https://tychesoftwares.freshdesk.com/a/tickets/37260)
