### ISSUE TITLE
Prices are not changing when the variation is changed.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/product-input-fields-for-woocommerce#46]
**Describe the bug**
Prices are not changing when the variation is changed.

**To Reproduce**
1) Pricing option does not enable at global and product level as well
2) Go to variation product frontend and try to change the variation but the price didn't change even if the variation is change

**Expected behavior**
The total should get changed when we change the variation.

**Screenshots**
https://www.screencast.com/t/dEXKWCjQ

**Comment by ashokrane** [comment]
The pricing option is not there in Lite plugin. Invalid issue, hence closing it.
