### ISSUE TITLE
The "Save Changes" button is missing on the "All Products: Field #1" setting page and Product level.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/product-input-fields-for-woocommerce#54]
**Describe the bug**
The "Save Changes" button is missing on the "All Products: Field # 1" setting page and Product level.

**To Reproduce**
1. PHP 8.0 setup
2. Take a live copy of the plugin that is v1.3.0
3. Go to the "All Products: Field # 1" setting page, the 'Save Changes ' button is missing

see the screenshot: https://www.screencast.com/t/oEd6s2oHCYt

Note: Same issue I am able to replicate on the edit product page. https://www.screencast.com/t/uKdRCP33

Because of the above issue, Input fields are not getting saved and I am not able to test this plugin with PHP 8.0

**Expected behavior**
The "Save Changes" button should be present at all places.

**Comment by Shasvat7** [comment]
@apeksha10 I am not able to replicate this issue with PHP 8.0 and the Save Changes button is coming fine on the 'All Products: Field #1' page. 
And on the edit product page, the save changes button will not come as we are not adding it there.
Hence, I am closing this issue.
screenshot: https://prnt.sc/1s5ys6s
