### ISSUE TITLE
When I add the shortcode for adding custom fields on product page, I'm unable to add the product to the cart. 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/product-input-fields-for-woocommerce#58]
**Describe the bug**
 I am having an issue with a custom text input field on this URL: https://www.woobamboo.com/product/custom-kids-bamboo-toothbrushes-6-pack/ Even with text input into the custom field, it seems to give off an error when the product is added to cart.

**To Reproduce**

1. Do this setup on the product page: https://prnt.sc/1qbkiuf
2. Select Position 'Do not display' on WooCommerce > Settings > Product Input Fields > General option and use '[alg_display_product_input_fields]' in product description.
3. Enter the text in custom field on product page, click on Add to Cart button
4. See error - https://prnt.sc/1qbkk3b

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/31992

**Comment by Shasvat7** [comment]
Same as #51
