### ISSUE TITLE
Date Picker and Time Picker JavaScript loads when not in use

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/product-input-fields-for-woocommerce#64]
**Describe the bug**
There's an option not to load the CSS and JavaScript of the date picker and time picker, which you can find in _/wp-admin/admin.php?page=wc-settings&tab=alg_wc_pif_ page. However, this option doesn't seem to work for JavaScript as the site still loads the JS for both the time picker and the date picker when not in use.

**Additional context**
[https://wordpress.org/support/topic/date-picker-and-time-picker-javascript-loading/](https://wordpress.org/support/topic/date-picker-and-time-picker-javascript-loading/)

**Comment by PratapDungrani** [comment]
@kartikparmar there's no option to disable JS. We only have option to enable/disable style.

**Comment by kartikparmar** [comment]
@PratapDungrani as discussed, we can change the label and description to 'Load Timepicker Style/Script
' and 'Enqueue Timepicker Style/Script' respectively and based on the same option we can add a check for JS files as well.
