### ISSUE TITLE
Field values not getting parsed to the cart

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/product-input-fields-for-woocommerce#80]
**Describe the bug**
This is a client-side issue that occurs on one of our plugin user's sites. The input field values do not get parsed to cart after clicking on the add to cart/submit button. 

To recreate the issue on the client's site, visit this page - [https://kidkrokodile.com.au/product/hand-made-timber-surfboard](https://kidkrokodile.com.au/product/hand-made-timber-surfboard). Add a text to the text input field on the frontend and add the product to the cart. From there, you'll see the error.

**Additional context**
[https://tychesoftwares.freshdesk.com/a/tickets/54501](https://tychesoftwares.freshdesk.com/a/tickets/54501)

**Comment by oluisrael11** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github issue #80](https://trello.com/c/RyspGyKt/4-github-issue-80)

**Comment by PratapDungrani** [comment]
The issue is with the theme. It is not compatible with WooCommerce and hence the user is experiencing the issue. I have investigated the issue and can confirm that the issue is not within our plugin. User needs to reach out to theme support.

**Comment by ashokrane** [comment]
@oluisrael11 Also on the theme's support page, you will see that there are others that have complained of the same thing: https://prnt.sc/aft1YEZ57PUD (link: https://themeforest.net/item/july-ecommerce-wordpress-theme/38120005/comments ) . You can share this as well with the client.
