### ISSUE TITLE
Add tracking data in plugin: Settings, admin choice and data tracking

### ISSUE THREAD

**Issue by pinalj** [TycheSoftwares/product-input-fields-for-woocommerce#84]
Describe the bug
Add the data tracking code in the plugin to ensure all the relevant details (global settings, product settings etc.) are sent back to the tracking server.

Additional context
https://docs.google.com/document/d/1T-4QcwvO1K-dZLFQwOxC_xvPjX4QFFXuSqt1bNn7lU4/edit

The tracking code needs to be implemented at v2

Tyche Javascript Constructor: https://github.com/TycheSoftwares/tyche-js-constructor
Plugin Tracking: https://github.com/TycheSoftwares/tyche-plugin-tracking
Plugin Deactivation: https://github.com/TycheSoftwares/tyche-plugin-deactivation

**Comment by apeksha10** [comment]
Re-opening this issue 

The database does not show Global/ Product level settings it just shows the active plugin and deactivate plugin lists.
https://app.screencast.com/1S84ygVwtXsZ9

I think we should track all plugin data including the Product/ Global level data.
